language: java
jdk:
 - oraclejdk8
notifications:
  email:
    recipients:
      - jonathanzgorski@gmail.com
      - ayoun1@students.towson.edu
    on_success: always # default: change
    on_failure: always # default: always
